# Site settings
title: Kaige Tan
# sgeneral_email:
academic_email: kaiget@kth.se

description: > # this means to ignore newlines until "baseurl:"
  Unit of Mechatronics and Embedded Control Systems,
  Brinellvägen 83,
  114 28, Stockholm, Sweden

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://KaigeTan.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username: github_username
linkedin_username: <a href="https://www.linkedin.com/in/kaige-tan-93a73a152/">Kaige Tan</a>
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
