# Site settings
title: Kaige Tan
email: edwin_tan@outlook.com

description: "Industrial AI | RL/ML | Intelligent Control Systems<br>Weir Digital Mineral, Malmö, Sweden"

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://KaigeTan.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username: github_username
linkedin_username: kaige-tan-93a73a152
orcid_id: 0000-0003-4535-3849
google_scholar_id: qA2Xb_MAAAAJ&hl=en
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
